"""four migration

Revision ID: 5fc9a3a1b235
Revises: 925db6d510ef
Create Date: 2018-04-23 16:53:42.109722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fc9a3a1b235'
down_revision = '925db6d510ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aboutme', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'aboutme')
    # ### end Alembic commands ###
