"""five migration

Revision ID: f0e630633b67
Revises: 5fc9a3a1b235
Create Date: 2018-04-23 17:40:04.058601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0e630633b67'
down_revision = '5fc9a3a1b235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_column('users', 'aboutme')
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', mysql.VARCHAR(length=11), nullable=False))
    op.add_column('users', sa.Column('aboutme', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
